-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 0.9.4
-- PostgreSQL version: 13.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: new_database | type: DATABASE --
-- DROP DATABASE IF EXISTS new_database;
CREATE DATABASE messaging_db;
-- ddl-end --


-- object: messaging_db | type: SCHEMA --
-- DROP SCHEMA IF EXISTS messaging_db CASCADE;
CREATE SCHEMA message_tracker;
-- ddl-end --
ALTER SCHEMA messaging_db OWNER TO postgres;
-- ddl-end --

SET search_path TO pg_catalog,public,messaging_db;
-- ddl-end --

-- object: messaging_db."user" | type: TABLE --
-- DROP TABLE IF EXISTS messaging_db."user" CASCADE;
CREATE TABLE messaging_db."user" (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	fullname text,
	username text,
	email text,
	phone_number text,
	CONSTRAINT user_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE messaging_db."user" OWNER TO postgres;
-- ddl-end --

-- object: messaging_db.message | type: TABLE --
-- DROP TABLE IF EXISTS messaging_db.message CASCADE;
CREATE TABLE messaging_db.message (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	subject text,
	content text,
	is_fecthed boolean,
	send_date date,
	CONSTRAINT message_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE messaging_db.message OWNER TO postgres;
-- ddl-end --

-- object: messaging_db.many_user_has_many_message | type: TABLE --
-- DROP TABLE IF EXISTS messaging_db.many_user_has_many_message CASCADE;
CREATE TABLE messaging_db.many_user_has_many_message (
	id_user integer NOT NULL,
	id_message integer NOT NULL,
	CONSTRAINT many_user_has_many_message_pk PRIMARY KEY (id_user,id_message)
);
-- ddl-end --

-- object: user_fk | type: CONSTRAINT --
-- ALTER TABLE messaging_db.many_user_has_many_message DROP CONSTRAINT IF EXISTS user_fk CASCADE;
ALTER TABLE messaging_db.many_user_has_many_message ADD CONSTRAINT user_fk FOREIGN KEY (id_user)
REFERENCES messaging_db."user" (id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: message_fk | type: CONSTRAINT --
-- ALTER TABLE messaging_db.many_user_has_many_message DROP CONSTRAINT IF EXISTS message_fk CASCADE;
ALTER TABLE messaging_db.many_user_has_many_message ADD CONSTRAINT message_fk FOREIGN KEY (id_message)
REFERENCES messaging_db.message (id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --


